### ISSUE TITLE
Blog - Email Capture component needs responsive design

### ISSUE THREAD

**Issue by jmmccasland** [shouldergiant/prototypal-ember#100]
<img width="400" alt="screen shot 2018-07-12 at 5 32 25 pm" src="https://user-images.githubusercontent.com/6935786/42663101-c4253ba8-85f9-11e8-8149-e9cff31c5c3a.png">

**Comment by shouldergiant** [comment]
Did not realize this was it's own issue, handled this in another push: 
https://github.com/shouldergiant/prototypal-ember/commit/42cf3dcd320cdd859a6e51ef59d5038820c7efe2
