### ISSUE TITLE
Blog - Article list needs responsive design

### ISSUE THREAD

**Issue by jmmccasland** [shouldergiant/prototypal-ember#101]
<img width="347" alt="screen shot 2018-07-12 at 5 33 43 pm" src="https://user-images.githubusercontent.com/6935786/42663125-e519714e-85f9-11e8-89dd-1b4e40cf2e5c.png">

**Comment by shouldergiant** [comment]
https://github.com/shouldergiant/prototypal-ember/commit/42cf3dcd320cdd859a6e51ef59d5038820c7efe2

Looks Like I did this last night and didn't tag it

**Comment by jmmccasland** [comment]
around 900px this explodes and breaks the layout. Most like a hard width issue. There's no reason that image should be the main focal point here. Might need to open another breakpoint to adjust it or give it the ability to be a little more fluid.

<img width="853" alt="screen shot 2018-07-16 at 11 41 08 am" src="https://user-images.githubusercontent.com/6935786/42771546-3d9eeb96-88ed-11e8-953c-bee45b40c1b4.png">
