### ISSUE TITLE
Index - Event card section broken

### ISSUE THREAD

**Issue by shouldergiant** [shouldergiant/prototypal-ember#103]
It looks like this must've gone awry after changing around the `training route event-cards`. Making an issue to make sure it's not lost in the laundry list. 

<img width="1155" alt="broken index event-card" src="https://user-images.githubusercontent.com/10280426/42670616-f29517d0-8629-11e8-8aed-e0805ef70cc6.png">

**Comment by jmmccasland** [comment]
@shouldergiant 
thanks for noting this! I actually fixed it up in my latest pr merge to develop, so i'm moving this to done and closing for now.

Also, @ebryn and I talked about converting this to a list of articles rather than events. Facundo should be working on that soon!
