### ISSUE TITLE
Index: "We've trained . . . " section

### ISSUE THREAD

**Issue by jmmccasland** [shouldergiant/prototypal-ember#12]
@shouldergiant 

I think there is some unnecessary margin being applied here. This image should probably span the full width of its container, and the text should be *almost, if not completely* visible in the viewport.

<img width="323" alt="screen shot 2018-06-11 at 3 40 08 pm" src="https://user-images.githubusercontent.com/6935786/41255959-d43b8df0-6d8d-11e8-8293-7dd35d383e08.png">

**Comment by shouldergiant** [comment]
Looks like I solved this with issue #13. didn't mean to double up commits (Whoops). Moving this to done for the time being.
