### ISSUE TITLE
contact-modal: bottom content not visible on smaller screen sizes

### ISSUE THREAD

**Issue by shouldergiant** [shouldergiant/prototypal-ember#17]
### The assistance number is not visible under certain screen sizes: 

<img width="413" alt="screen shot 2018-06-13 at 8 17 24 pm" src="https://user-images.githubusercontent.com/10280426/41385006-0b447086-6f47-11e8-9bf5-6930322b862c.png">
<img width="324" alt="screen shot 2018-06-13 at 8 17 46 pm" src="https://user-images.githubusercontent.com/10280426/41385009-0ef2ccbe-6f47-11e8-8007-c51d79ffd55f.png">

**Comment by jmmccasland** [comment]
@shouldergiant

i forgot to mention, you might be able to use the `overflow` property to fix this bug.

`overflow-y: scroll;`, for example should allow users to scroll if the modal is too tall.
