### ISSUE TITLE
Contact link in nav bar should have pointer cursor

### ISSUE THREAD

**Issue by jmmccasland** [shouldergiant/prototypal-ember#20]
@shouldergiant 

Might want to add `cursor: pointer;` to your button reset so that it signals a link to follow or action to perform when users hover over things.

**Comment by shouldergiant** [comment]
@jmmccasland Came across the other cursor issues before this one. I added `cursor: pointer;` to the button reset, I'll go back and clean up the specific button styles that no longer need it because of it existing now in the reset.
