### ISSUE TITLE
Contact Modal: Remove input outline and add custom border on focus

### ISSUE THREAD

**Issue by jmmccasland** [shouldergiant/prototypal-ember#21]
@shouldergiant 

Remove the outline when focusing an input in the contact modal and instead make the bottom border the primary green color.

Also, extra reading for accessibility regarding outlines and why they're important: https://a11yproject.com/posts/never-remove-css-outlines/

<img width="594" alt="screen shot 2018-06-14 at 2 06 38 pm" src="https://user-images.githubusercontent.com/6935786/41432632-42a2022e-6fdc-11e8-8fc8-b594c3521234.png">

**Comment by jmmccasland** [comment]
@shouldergiant 

i think you misunderstood.

To close this issue, we need to meet these 3 criteria:
- [ ] By default / unfocused, the border bottom color is the original white/grey.

- [ ] When clicking (focusing) on the input, the border turns green

- [ ] When focusing on the input, there is no 'outline'.

**Comment by shouldergiant** [comment]
@jmmccasland I did read the instruction incorrectly my bad. This should work correctly now :D

**Comment by jmmccasland** [comment]
@shouldergiant 

looks good!
