### ISSUE TITLE
Company: Hero text padding

### ISSUE THREAD

**Issue by jmmccasland** [shouldergiant/prototypal-ember#28]
There should be some padding on the edges here so the text doesn't butt up against the edge of the screen.

<img width="378" alt="screen shot 2018-06-14 at 2 28 09 pm" src="https://user-images.githubusercontent.com/6935786/41433662-38a16dfc-6fdf-11e8-90eb-cf85f66323ae.png">

**Comment by shouldergiant** [comment]
@jmmccasland Looks like I may have solved this without its own commit. 👍 Moving it to done for the time being
