### ISSUE TITLE
Training: Contact Input

### ISSUE THREAD

**Issue by jmmccasland** [shouldergiant/prototypal-ember#35]
@shouldergiant 

this input needs some padding on the left side to keep the placeholder text off of the side
<img width="774" alt="screen shot 2018-06-14 at 2 48 22 pm" src="https://user-images.githubusercontent.com/6935786/41434656-177d0cf0-6fe2-11e8-933c-c7b2d22076ae.png">

**Comment by shouldergiant** [comment]
@jmmccasland previously made this change in my PR request yesterday (6/13). Moving to Done for the time being

**Comment by jmmccasland** [comment]
@shouldergiant 

🤔 hmmm, i'm not seeing it on `master` or the `contact-modal` branch.

<img width="757" alt="screen shot 2018-06-15 at 8 54 10 am" src="https://user-images.githubusercontent.com/6935786/41471617-c79070f4-7079-11e8-938e-c536c5ee8a39.png">

**Comment by shouldergiant** [comment]
@jmmccasland this should be good now. I had input padding in the media query styles :-\ haha
