### ISSUE TITLE
Global: Use CSS to add green border on elements like this

### ISSUE THREAD

**Issue by jmmccasland** [shouldergiant/prototypal-ember#8]
@shouldergiant 

We should use pseudo elements or borders/box-shadows etc to achieve this green accent on these images. That way, if Eric wants to change his picture to [this](https://twitter.com/amatchneer/status/1000151748558970886) he won't have to open up sketch/AI/PS etc to add that border. 

These cards should also extend 100% of their container on mobile, but again, i bet its other images/text breaking the layout causing them to appear like they're not. 

<img width="381" alt="screen shot 2018-06-08 at 4 40 47 pm" src="https://user-images.githubusercontent.com/6935786/41182434-3e89d1d0-6b3b-11e8-8e72-991d966be763.png">

**Comment by jmmccasland** [comment]
@shouldergiant 

there's still a few images that need this update. there might be more, but these are the two i noticed.

<img width="1322" alt="screen shot 2018-06-15 at 8 51 12 am" src="https://user-images.githubusercontent.com/6935786/41471456-4dfd5086-7079-11e8-81be-725a8758cb15.png">
<img width="1263" alt="screen shot 2018-06-15 at 8 51 00 am" src="https://user-images.githubusercontent.com/6935786/41471457-4e0ea430-7079-11e8-89ed-c91aa9e08235.png">

**Comment by shouldergiant** [comment]
@jmmccasland Dunno how I missed these :S ! I switched the images to ones that don't have a box shadow (there are duplicates now as placeholders until I can get a non-trial sketch app and get to the sketch file to get ones without the box-border) Also, I noticed that I was using box shadow everywhere, So I created a variable in the app.scss and then created a box-shadow reset - that way I can just plug it into the markup. Seems to work OK unless its not a great practice.

**Comment by jmmccasland** [comment]
@shouldergiant 

Creating variables for frequently used properties is a great practice. Good work!

Closing this now because it seems complete.
