### ISSUE TITLE
Blog - Cleanup Hero

### ISSUE THREAD

**Issue by jmmccasland** [shouldergiant/prototypal-ember#98]
@shouldergiant 

Similar issue to training, let's make sure we're using the exisiting `hero` styles. I don't think we should need to add any additional styling here except to maybe hide the psuedo class. 

So let's just add a modifier class to the hero-title in typography.scss:
```
  &--no-psuedo {
    &::after {
      display: none;
    }
  }
```

**Comment by shouldergiant** [comment]
Also did this earlier in a different commit. Didn't realize it was on it's own issue: 

https://github.com/shouldergiant/prototypal-ember/commit/eb01465f66c4595de07a4baa16923255bda86762#diff-41de023ab8661ef7a055a67fbabf05f2
